faktory-connection-info:
    port: 7419
    domain: faktory
db-connection-info:
    domain: mongo
    port: 27017
    user:
    password:
    database: tanglenomicon
tangle-collections:
    stencil_col_name: arborescent_stencils
    col_name: arborescent_tangles
    page_size: 500
