name: CMake

on:
    pull_request:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
                  submodules: recursive
                  fetch-depth: 0

            - name: Check Nixpkgs inputs
              uses: DeterminateSystems/flake-checker-action@main
              with:
                  fail-mode: true

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Prettier
              run: |
                  nix develop --command \
                      just check-prettier

            - name: ruff
              run: |
                  nix develop --command \
                      just check-ruff

            - name: Build
              run: |
                  nix develop --command \
                      just build-wrapper

            - name: Test
              run: |
                  nix develop --command \
                    just test-all

            - name: Docs
              run: |
                  nix develop --command \
                      just docs
