name: Create release

on:
    push:
        tags:
            - "v*.*.*"

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Check Nixpkgs inputs
              uses: DeterminateSystems/flake-checker-action@main
              with:
                  fail-mode: true

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Prettier
              run: |
                  nix develop --command \
                      just check-prettier

            - name: C-format
              run: |
                  nix develop --command \
                      just check-uncrustify

            - name: Build
              run: |
                  nix develop --command \
                      just build_all

            - name: Test
              run: |
                  nix develop --command \
                    just test_all


            - name: Zip Docs
              run: |
                  nix develop --command \
                    just zip

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      ./Library_Documentation.zip